### PR TITLE
Travis builds and PHPUnit

### PR DESCRIPTION
**Pull request by h4cc**
Failing against symfony 2.1 https://travis-ci.org/h4cc/cache-bundle/builds/45606005

### CODE REVIEW

**Comment by aequasi** [comment]
Yeah, lets just change it to `>=2.2.0,<3.0`...

**Comment by aequasi** [comment]
If its not a huge change, you could change it to `symfony/framework` too. Otherwise i can do that after

**Comment by h4cc** [comment]
I removed symfony 2.1 from composer and travis.

Chaging symfony/symfony to symfony/framework-bundle needs to be verified to a working symfony application using this bundle. I think you should do that...

**Comment by aequasi** [comment]
Sounds good.

**Comment by aequasi** [comment]
You ready to have this merged?

**Comment by h4cc** [comment]
Yes, can be merged :+1:

**Pull request merged**
